# Generated by Django 5.2 on 2025-05-26 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(blank=True, max_length=100)),
                ('memory', models.CharField(blank=True, max_length=100)),
                ('display', models.CharField(blank=True, max_length=100)),
                ('storage', models.CharField(blank=True, max_length=100)),
                ('graphics', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('finish', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.productspecification'),
            preserve_default=False,
        ),
    ]
