# Generated by Django 5.2 on 2025-05-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_date_review_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='my_order',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
    ]
