# Generated by Django 5.2.1 on 2025-06-10 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_product_specs_productspecification_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atribute',
            new_name='Attribute',
        ),
        migrations.RenameModel(
            old_name='AtributeKey',
            new_name='AttributeKey',
        ),
        migrations.RenameModel(
            old_name='AtributeValue',
            new_name='AttributeValue',
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='atribute_key',
            new_name='attribute_key',
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='atribute_value',
            new_name='attribute_value',
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
    ]
