# Generated by Django 5.2 on 2025-06-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_atribute_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
